### PR TITLE
Jira Kanban mode

### PR DESCRIPTION
**Pull request by froznsm**
Adds #7. 

Some additional changes worth mentioning:
 - renamed `updateCurrentSprint` to `update`
 - added variations of a few helper functions

Thorough testing is needed, but it works like my hacked together version now. 

All feedback and change requests are welcome :)

### CODE REVIEW

**Comment by bcwilsondotcom** [comment]
Would love to see this get merged

**Comment by BoxThatBeat** [comment]
Hey @froznsm this is great stuff! I did some testing and found some bugs and I am working on some improvements. I wanted your opinion on a potential change. To reduce the complexity of having to manually add the column names of the board, I was thinking we could get the board config and just by default get all tasks from that board and then just take the last column as the "final" by default. Then provide an optional comma-separated list of custom "final" columns. This does limit the user since they can't decide which columns to import but I believe that is still better. What do you think?

**Comment by BoxThatBeat** [comment]
Feel free to email me at aaron.buitenwerf@carleton.ca if that is easier than discussing here.

**Comment by BoxThatBeat** [comment]
Some changes I've made so far:

- Any notes that were final before they were made in Obsidian would not get created and put in the final folder -fixed
- Added the Kanban board creation. Even if it's something not all users wish to use, there is always the option to turn it off in settings.
- Added a trim on the comma-separated lists so that if there are spaces after the commas, it will remove them
- Changed where we get status from in the response: status.statusCategory.name to status.name (bug)

**Comment by BoxThatBeat** [comment]
So my proposed next change would be this:
- Make a simple request to get all issues assigned to the user on the board (no check for status)
- Have a comma separated list of final states, and simply filter those from the returned list (less API requests)
- If that list of final states is empty, take the last column of the configuration by default

**Comment by froznsm** [comment]
Thanks for the improvements, fixes and suggestions @BoxThatBeat! 

> Some changes I've made so far:
> 
> * Any notes that were final before they were made in Obsidian would not get created and put in the final folder -fixed
> * Added the Kanban board creation. Even if it's something not all users wish to use, there is always the option to turn it off in settings.
> * Added a trim on the comma-separated lists so that if there are spaces after the commas, it will remove them
> * Changed where we get status from in the response: status.statusCategory.name to status.name (bug)

Good stuff!

> So my proposed next change would be this:
> 
> * Make a simple request to get all issues assigned to the user on the board (no check for status)
> * Have a comma separated list of final states, and simply filter those from the returned list (less API requests)
> * If that list of final states is empty, take the last column of the configuration by default

This approach could certainly work and is more flexible than what I did, so I guess for future proofing this would be better. :+1: from me.

**Comment by BoxThatBeat** [comment]
Alright I'll try that out and see if it works well! By the way, what is the use case to have multiple "final" state statuses? @froznsm

**Comment by froznsm** [comment]
The ones we use at work are `Done` and `Won't do`. Sometimes an issue can get passed around, be estimated, stay in impeded, whatever and it might be decided that it is not worth it and will be moved to `Won't do`. The distinction of final states really serves  documentation purposes. The obsidian note that might have been created during this time should still be moved to the final folder.

**Comment by BoxThatBeat** [comment]
Hmm makes sense!

**Comment by BoxThatBeat** [comment]
Hey @froznsm! I made quite a few changes to how this all works and I think it is in a good state. Could you pull the changes and test it out in your use case and let me know how it goes before I merge this? The major change I made was removing all new settings except the toggle between modes. It now determines which files should be in the "completed" folder (renamed from final) by checking for the existence of a field called "resolution" which is Jira's marker for a finished issue. All columns that should mark tasks as complete should have a check mark beside them:
image

You can assign columns this "resolution" designation in settings or with simple Kanban boards it is the "done" state in the workflow.

**Comment by froznsm** [comment]
@BoxThatBeat I have tested the changes and they do work, as in there are not obvious bugs. Good work!

One unfortunate side-effect of your implementation is however, that notes are created for backlog items as well (at least with our board config). I would prefer to only have notes for tickets that currently are in progress, which is why I implemented the setting to make this part configurable. I don't mind it much, so if you feel this way is better, you can merge.

**Comment by BoxThatBeat** [comment]
@froznsm Thanks! Ya I did notice that when I did testing. I wonder if I could just add a boolean setting for whether to include the backlog items or not. I assume the name of the backlog would never change and thus could just be string compared to get rid of it?

**Comment by BoxThatBeat** [comment]
@froznsm Could you try out the new toggle for excluding the backlog I just added? If it works on your system I'll merge it!

**Comment by BoxThatBeat** [comment]
@froznsm Do you plan on testing or should I just merge it?

**Review by BoxThatBeat — APPROVED** [review]
Works great!

**Pull request merged**
